In [1]:
import numpy as np

In [3]:
scalar=np.array(42)
print(scalar)
scalar.ndim

42


0

In [6]:
vector=np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [8]:
matriz=np.array([[1,2,3],
                 [4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [27]:
tensor=np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [40,50,60]],
                  [[15,26,38],
                   [54,1,0],
                   [17,9,1],
                   [0,5,355]]])
print('-'*10)
print(f'Tensor: \n {tensor}')
print('-'*10)
print(f'el tensor tiene {tensor.ndim} dimensiones')
print('-'*10)
print(f'el elemento N° cero del tensor es la matriz \n {tensor[0]} ')
print('-'*10)
print(f'el elemento N° (1,1) del tensor es el vector \n {tensor[1,1]}')
print('-'*10)
print(f'el elemento N° (1,3,3) del tensor es el escalar \n {tensor[1,3,2]}')

----------
Tensor: 
 [[[  1   2   3]
  [  4   5   6]
  [  7   8   9]
  [ 40  50  60]]

 [[ 15  26  38]
  [ 54   1   0]
  [ 17   9   1]
  [  0   5 355]]]
----------
el tensor tiene 3 dimensiones
----------
el elemento N° cero del tensor es la matriz 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [40 50 60]] 
----------
el elemento N° (1,1) del tensor es el vector 
 [54  1  0]
----------
el elemento N° (1,3,3) del tensor es el escalar 
 355


### Agregar o eliminar dimensiones

Definimos un arreglo con 10 dimensiones, a pesar de incluir un solo elemento llamado vector

In [28]:
vector=np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10


Usamos el comando para expandir las dimensiones de nuestro vector, a pesar de que el array definido `np.array([[1,2,3],[1,2,3]]` solo tiene dos dimensiones,
usamos el método `np.expand_dims(array,axis= 0 para_filas ó 1 para_columnas)` para añadir una dimensión más. Si el parametro `axis=0` añade una dimensión a las filas

In [39]:
expand = np.expand_dims(np.array([[1,2,3],[1,2,3]]),axis=0)
print(expand)
print(expand.ndim)
len(expand)


[[[1 2 3]
  [1 2 3]]]
3


1

Si `axis=1` añade una dimensión a las columnas

In [37]:
expand = np.expand_dims(np.array([[1,2,3],[1,2,3]]),axis=1)
print(expand)
print(expand.ndim)
len(expand)


[[[1 2 3]]

 [[1 2 3]]]
3


2

### Reducir la dimensionalidad de un array

Podemos reducir las dimensiones de un arreglo con el metodo `np.squeeze(array)` que retorna un array con las dimensiones utiles

In [45]:
print('vector {} de {} dimensiones'.format(vector,vector.ndim))
vector_reducido=np.squeeze(vector)
print('vector reducido {} de {} dimensiones'.format(vector_reducido,vector_reducido.ndim))


vector [[[[[[[[[[1 2 3]]]]]]]]]] de 10 dimensiones
vector reducido [1 2 3] de 1 dimensiones
