In [3]:
import numpy as np

Creamos una lista

In [1]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Ahora creamos un array con Numpy `np.arange(limite_inferior, limite_superior, step_o_salto)`

In [5]:
print(f'arreglo_1: {np.arange(0,20)}')
print(f'arreglo con step: {np.arange(0,20,2)}')

arreglo_1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
arreglo con step: [ 0  2  4  6  8 10 12 14 16 18]


Creamos arrays de ceros o unos del tamaño y dimensiones deseado

In [17]:
print(np.zeros((3,3,4)))
np.ones((3,3))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Podemos generar arreglos de manera mas especifica con `np.linspace(limite_inferior, limite_superior, cantidad_de_datos)`

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Pueden crearse sistemas matriciales de diagonal principal en 1 con `np.eye(tamaño_de_la_matriz)`

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Generación de arrays con valores aleatorios

Generamos valores aleatorios entre `0` y `1` con `np.random.rand()`

In [22]:
np.random.rand()

0.6422644472954455

Si agregamos un argumento nos genera un array de valores aleatorios entre `0` y `1` del tamaño que le indiquemos

In [25]:
np.random.rand(3,2)

array([[0.05266429, 0.66342433],
       [0.55252386, 0.11611551],
       [0.58571546, 0.67230001]])

Generamos un valor entero aleatorio en el rango especificado con `np.random.randint(1,15)`

In [30]:
np.random.randint(1,50)

15

Tambien se pueden generar arrays completos de un tamaño especificado en un rango dado `np.random.randint(1,100,(5,5))`. Este comando genera una matriz aleatoria de `5 x 5` con valores entre `1` y `100`

In [31]:
np.random.randint(1,100,(5,5))

array([[27, 56, 13, 62, 20],
       [20, 98, 84, 98, 31],
       [65, 43, 70, 39, 10],
       [57, 82, 92, 95, 90],
       [62, 12, 93,  6, 61]])