In [34]:
import numpy as np

In [35]:
arr = np.random.randint(1,10,(3,2))

`arr.shape` permite saber la dimensionalidad de un arreglo

In [36]:
arr.shape

(3, 2)

Es posible reacomodar la forma de la matriz con `arr.reshape()`

In [37]:
print(arr)

[[6 5]
 [4 7]
 [9 4]]


In [38]:
print(arr.reshape(1,6))
np.reshape(arr,(1,6))

[[6 5 4 7 9 4]]


array([[6, 5, 4, 7, 9, 4]])

In [39]:
print(arr.reshape(2,3))
np.reshape(arr,(2,3))

[[6 5 4]
 [7 9 4]]


array([[6, 5, 4],
       [7, 9, 4]])

In [43]:
arr

array([[6, 5],
       [4, 7],
       [9, 4]])

Podemos hacer el reshape como lo haria el lenguaje C, ordenando los datos por filas

In [41]:
np.reshape(arr,(2,3),'C')

array([[6, 5, 4],
       [7, 9, 4]])

O puede hacerlo como lo haria el lenguaje Fortrand ordenando los datos por columnas

In [44]:
np.reshape(arr,(2,3),'F')

array([[6, 9, 7],
       [4, 5, 4]])

O puede hacerlo de acuerdo a lo que mejor se optimize según el guardado de datos en memoria en mi sistema, lo puede hacer con el lenguaje C o Fortrand según convenga

In [45]:
np.reshape(arr,(2,3),'A')

array([[6, 5, 4],
       [7, 9, 4]])