In [91]:
import numpy as np  

In [92]:
arr = np.random.randint(1,20,10)
matriz = arr.reshape(2,5)
print(matriz)

[[ 8 10  8  7  8]
 [15 17 16  9  9]]


### Funciones principales de `Numpy`
 - `.max `: retorna el numero más grande que contiene un array

In [93]:
print(arr.max())
print(matriz)

17
[[ 8 10  8  7  8]
 [15 17 16  9  9]]


Es posible navegar en las dimensiones del array para que retorne el número mayor en una de ellas, en una matriz sería o por filas o por columnas


In [94]:
#POR FILAS
print(f'Maximos por filas : {matriz.max(1)}')
#POR COLUMNAS
print(f'Maximos por columnas : {matriz.max(0)}')

Maximos por filas : [10 17]
Maximos por columnas : [15 17 16  9  9]


Tambien es posible obtener la posición en la cual se ubica el valor maximo en el array

- `.argmax( )`: devuelve la posición en el array del número maximo, si el número maximo se encuentra repetido solo retorna la posición de menor valor

In [95]:
arr.argmax()

6

Tambien es posible saber la posición según la dimensión especificada, recordar que devuelve arrays de posición

In [96]:
print(matriz)
print()
#POR FILAS
print(matriz.argmax(1))
#POR COLUMNAS
print(matriz.argmax(0))


[[ 8 10  8  7  8]
 [15 17 16  9  9]]

[1 1]
[1 1 1 1 1]


Por supuesto existe la función homologa para obtener el valor o valores mínimos de un array

- `.min( )`: retorna el valor mínimo de un array. puede recibir como argumento la dimensión de un array en la cual se quieren buscar los valores minimos

In [97]:
arr

array([ 8, 10,  8,  7,  8, 15, 17, 16,  9,  9])

In [98]:
arr.min()

7

In [99]:
matriz

array([[ 8, 10,  8,  7,  8],
       [15, 17, 16,  9,  9]])

In [100]:
#POR COLUMNAS
print(f'Minimos por columnas {matriz.min(0)}')
#POR COLUMNAS
print(f'Minimos por filas {matriz.min(1)}')

Minimos por columnas [ 8 10  8  7  8]
Minimos por filas [7 9]


Usamos `.argmin( )` para saber cuales son los indices en los cuales se encuentran esos valores

In [101]:
arr.argmin()

3

In [102]:
#POR COLUMNAS
print(f'indices de los minimos por columnas {matriz.argmin(0)}')
#POR COLUMNAS
print(f'indices de los minimos por filas {matriz.argmin(1)}')

indices de los minimos por columnas [0 0 0 0 0]
indices de los minimos por filas [3 3]


- `.ptp( )`:peak to peak 
            Retorna la diferencia entre el valor minimo y el valor máximo en un array

In [103]:
arr

array([ 8, 10,  8,  7,  8, 15, 17, 16,  9,  9])

In [104]:

print(arr.ptp())
print(f'Retorna {arr.ptp()} porque el valor maximo del array es {arr.max()} y el valor minimo es {arr.min()}\n{arr.max()} - {arr.min()} = {arr.ptp()} ')


10
Retorna 10 porque el valor maximo del array es 17 y el valor minimo es 7
17 - 7 = 10 


Igual que las otras funciones funciona para determinar esa diferencia en dimensiones dadas de un array

In [105]:
#genero un rango con el numero de columnas de la matriz
#me va a servir para recorrerla
print(range(matriz.shape[1]))

range(0, 5)


In [106]:
print(matriz)
print()
#POR FILAS
for fila in matriz:
    print(f'{fila.max()} - {fila.min()} = {fila.ptp()}') 
print(f'peak_to_peak por filas {matriz.ptp(1)}')
print()
#POR COLUMNAS
for j in range(matriz.shape[1]):
    columna = matriz[:, j]
    print(f'{columna.max()} - {columna.min()} = {columna.ptp()}')

print(f'peak_to_peak por columnas {matriz.ptp(0)}')

[[ 8 10  8  7  8]
 [15 17 16  9  9]]

10 - 7 = 3
17 - 9 = 8
peak_to_peak por filas [3 8]

15 - 8 = 7
17 - 10 = 7
16 - 8 = 8
9 - 7 = 2
9 - 8 = 1
peak_to_peak por columnas [7 7 8 2 1]


Se pueden calcular los `cuantiles` de la distribución del array, ya sea en:
- ``cuartiles``: 4 partes iguales (cuantiles 0.25; 0.50 y 0.75 )
- ``quintiles``: 5 partes iguales (cuantiles 0.20; 0.40; 0.60 y 0.80)
- ``deciles``: 10 partes iguales
- ``percentiles``: 100 partes iguales

Utilizamos las funciones
- `np.cuantile(datos,cuantil)` 
- `np.percentile(datos,percentil)`

En ambas ponemos como argumentos los datos y el cuantil o percentil que queremos calcular. Si somos listos podemos obtener cualquier cuartil, quintil, decil o percentil.

- ``cuartiles``

In [107]:
print(arr)
 
quartiles= np.quantile(arr, [0.25,0.50,0.75])
quartiles_v2 =np.percentile(arr,[25,50,75])
print('cuartiles')
print(quartiles)
print(quartiles_v2)

[ 8 10  8  7  8 15 17 16  9  9]
cuartiles
[ 8.    9.   13.75]
[ 8.    9.   13.75]


- `quintiles`

In [108]:
print(arr)
 
quintiles= np.quantile(arr, [0.20,0.40,0.60,0.80])
quintiles_v2 =np.percentile(arr,[20,40,60,80])
print('quintiles')
print(quintiles)
print(quintiles_v2)

[ 8 10  8  7  8 15 17 16  9  9]
quintiles
[ 8.   8.6  9.4 15.2]
[ 8.   8.6  9.4 15.2]


- ``deciles``

In [109]:
print(arr)

deciles = np.percentile(arr, np.arange(10, 100, 10))
deciles_v2=np.quantile(arr, np.arange(0.1,1,0.1))
print('deciles')
print(deciles)
print(deciles_v2)


[ 8 10  8  7  8 15 17 16  9  9]
deciles
[ 7.9  8.   8.   8.6  9.   9.4 11.5 15.2 16.1]
[ 7.9  8.   8.   8.6  9.   9.4 11.5 15.2 16.1]


- ``percentiles``

In [110]:
print(arr)

percentiles = np.percentile(arr, np.arange(1, 100))
percentiles_v2=np.quantile(arr, np.arange(0.01,1,0.01))
print('deciles')
print(percentiles)
print(percentiles_v2)

#calcular el percentil 50

percentil_50 = np.percentile(arr,50)
print( f'\nel percentil 50 del array es: {percentil_50}')

[ 8 10  8  7  8 15 17 16  9  9]
deciles
[ 7.09  7.18  7.27  7.36  7.45  7.54  7.63  7.72  7.81  7.9   7.99  8.
  8.    8.    8.    8.    8.    8.    8.    8.    8.    8.    8.    8.
  8.    8.    8.    8.    8.    8.    8.    8.    8.    8.06  8.15  8.24
  8.33  8.42  8.51  8.6   8.69  8.78  8.87  8.96  9.    9.    9.    9.
  9.    9.    9.    9.    9.    9.    9.    9.04  9.13  9.22  9.31  9.4
  9.49  9.58  9.67  9.76  9.85  9.94 10.15 10.6  11.05 11.5  11.95 12.4
 12.85 13.3  13.75 14.2  14.65 15.02 15.11 15.2  15.29 15.38 15.47 15.56
 15.65 15.74 15.83 15.92 16.01 16.1  16.19 16.28 16.37 16.46 16.55 16.64
 16.73 16.82 16.91]
[ 7.09  7.18  7.27  7.36  7.45  7.54  7.63  7.72  7.81  7.9   7.99  8.
  8.    8.    8.    8.    8.    8.    8.    8.    8.    8.    8.    8.
  8.    8.    8.    8.    8.    8.    8.    8.    8.    8.06  8.15  8.24
  8.33  8.42  8.51  8.6   8.69  8.78  8.87  8.96  9.    9.    9.    9.
  9.    9.    9.    9.    9.    9.    9.    9.04  9.13  9.22  9.31  9.4
  9.49

Ordenación de datos en un array

- `np.sort( )`: ordena de menor a mayor un array modificando la lista `**original**`

In [111]:
arr.sort()
arr


array([ 7,  8,  8,  8,  9,  9, 10, 15, 16, 17])

## Calcular medidas de tendencia central

### Media
- `np.mean(data)`: calcula la media o promedio de la distribucion dada

In [112]:
media = np.mean(arr)
print(f'la media de los datos del array es {media}')
print()
print(f'la media de los datos de la matriz por columnas (eje 1) es {np.mean(matriz,1)}')

la media de los datos del array es 10.7

la media de los datos de la matriz por columnas (eje 1) es [ 8.  13.4]



### Mediana
- `np.median(data)`: calcula la mediana de la distribución

In [113]:
mediana = np.median(arr)
print(f'la mediana de la distribución es: {mediana}')
percentil_50 = np.percentile(arr,50)
print( f'\nel percentil 50 del array es: {percentil_50}')

print(f'la mediana del eje 0 de la matriz es {np.median(matriz,1)}')

la mediana de la distribución es: 9.0

el percentil 50 del array es: 9.0
la mediana del eje 0 de la matriz es [ 8. 15.]


### Moda

Numpy no posee un metodo directo para el calculo de la moda, instalaremos el paquete SciPy e importaremos el modulo stats para calcularla

-`stats.mode(data)`: devuelve un objeto llamado **ModeResult** en el cual se indica el valor modal ('mode') y la frecuencia modal ('count'), tambien posee otro argumento opcional (keepdims = `True` or `False`) el cual puede hacer que la funcion mantenga o no las mismas dimensiones que el array original en su salida

In [114]:

from scipy import stats
moda = stats.mode(arr)
valor_modal = moda.mode
frecuencia_modal = moda.count

print("Valor modal:", valor_modal)
print("Frecuencia modal:", frecuencia_modal)


Valor modal: [8]
Frecuencia modal: [3]


/tmp/ipykernel_16803/732047997.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  moda = stats.mode(arr)


### Desviación estandar

- `np.std(data)`: calcula la desviación estandar de la distribución

In [115]:
desv_stand = np.std(arr)
print(f'la desviación estandar de la distribución del array  es: {desv_stand}')
print(f'la desviación estandar de la matriz en el eje 0 es {np.std(matriz,0)}')

la desviación estandar de la distribución del array  es: 3.579106033634656
la desviación estandar de la matriz en el eje 0 es [1.  1.  3.5 4.  4. ]


### Varianza 

- `np.var( )`: calcula la varianza de la distribución

In [116]:
#elevamos al cuadrado la desviación estandar
var= desv_stand **2
print(f'la varianza del array es: {var}')
var = np.var(arr) 
print(f'la varianza del array es: {var}')
print('-'*5)
print(f'la varianza de la matriz en el eje 0 es {np.var(matriz,0)}')

la varianza del array es: 12.809999999999999
la varianza del array es: 12.809999999999999
-----
la varianza de la matriz en el eje 0 es [ 1.    1.   12.25 16.   16.  ]


Concatenar arrays

In [117]:
#Creamos dos arrays
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [118]:
np.concatenate((a,b),axis=0)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [119]:
#Evaluamos las dimensiones 
print(a.ndim) # 2 dims
print(b.ndim) # 1 dim
#añadimos una dimensión a b y resolvemos el error
b = np.expand_dims(b,axis=0)
b

2
1


array([[5, 6]])

In [120]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

Utilizamos la transpuesta de la matriz B para poder hacer la concatenacion, tambien funcionaria si hicieramos un reshape

In [121]:
#Utilizamos la transpuesta de la matriz B para poder hacer la concatenacion
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])