In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
trozo_de_arr = arr[0:6]
trozo_de_arr[:]=0
print(trozo_de_arr)
arr

[0 0 0 0 0 0]


array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Como se puede observar, realizar transformaciones sobre un arreglo o dataframe de esta manera modifica el conjunto original de datos, a pesar de que aparentemente estamos guardando el trozo en una nueva variable. Para evitar esto y salvaguardar nuestro conjunto de datos es recomendable siempre realizar una copia del mismo, utilizaremos la siguiente función:

- `data.copy( )`:realiza una copia en memoria de la data que le indiquemos, no modificará la lista original.

In [6]:
arr_copy = arr.copy()
print(arr_copy)

[ 0  0  0  0  0  0  6  7  8  9 10]


In [7]:
arr_copy[:] = 100

In [8]:
print(f'array original \n {arr}')
print(f'copia del array \n {arr_copy}')

array original 
 [ 0  0  0  0  0  0  6  7  8  9 10]
copia del array 
 [100 100 100 100 100 100 100 100 100 100 100]
