In [1]:
import numpy as np

In [6]:
arr = np.linspace(1,10,10, dtype= 'int8')

Si realizamos condicionales se obtiene los siguiente

In [7]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Podemos observar que se genera una lista con valores booleanos de acuerdo a la condicion dada.

Tambien podemos obtener el array de los valores que cumplan la condicion propuesta, veamos

In [10]:
indices_cond = arr > 5
arr[arr>5]
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [11]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [13]:
arr[arr > 5] = 99

In [15]:
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)