In [1]:
import numpy as np

In [3]:
lista = [1,2]
lista

[1, 2]

In [5]:
lista * 2

[1, 2, 1, 2]

Se puede ver que python no comprende que queremos multiplicar cada elemento de la lista por 2. En cambio duplica la lista y la concatena, para realizar la operación matematica procederemos de la siguiente manera

### Operaciones Aritméticas con Numpy

In [9]:
#creamos un array
arr = np.arange(0,10)
arr2 = arr.copy()

In [10]:
#multiplicamos
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
#sumamos
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
#Dividimos
1/arr

/tmp/ipykernel_485/1166940612.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Arroja un warning que indica que no se puede dividir entre 0, por lo tanto en la primera posicion existe un valor indefinido, no obstante `NO ARROJA ERROR O ALGUNA EXCEPCION` y continua con el programa, realizando las operaciones restantes

In [14]:
#elevamos al cuadrado
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
#Operaciones entre arrays
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [22]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

print(matriz)
print(matriz2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
#operaciones entre matrices
matriz + matriz2    

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [26]:
######Producto punto de matrices
print('recordamos que debe ser con  la transpuesta para que coincidan filas de M1 con columnas de M2')

matriz2.T
np.matmul(matriz, matriz2.T)


recordamos que debe ser con  la transpuesta para que coincidan filas de M1 con columnas de M2


array([[ 30,  80],
       [ 80, 255]])

In [29]:
#Otra manera de hacer producto punto
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])